name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true
      - run: yarn install --immutable
      - run: yarn run format:ci
      - run: yarn run build:ci
      - run: yarn run test:ci
